
# 环境配置
server:
  # 服务端口
  port: 35260

spring:
  datasource:
    name: lbs-cache
    url: jdbc:mysql://127.0.0.1:3306/LocationService?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zdxk.locationservice
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/*Mapper.xml
  # 加载全局的配置文件
  # configLocation: classpath:mybatis/mybatis-config.xml

api:
  baiduAk:
  lbs: